[package]
name = "min_moves_462"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
divan = "0.1.13"

[dev-dependencies]
divan = "0.1.13"

[[bench]]
name = "example"
harness = false
